Keyring & populate common:
Docker templates:
 - Fixed problem with keyring symlink in common
 - Modified populate-common script to add appropriate folder for keyring
 - Working on db/cassandra Dockerfile

diff --git a/docker-templates/db/cassandra/common/install-cassandra b/docker-templates/db/cassandra/common/install-cassandra
--- a/docker-templates/db/cassandra/common/install-cassandra
+++ b/docker-templates/db/cassandra/common/install-cassandra
@@ -1,20 +1,47 @@
-#!/bin/bash
+#!/bin/sh
+# Licensed to the Apache Software Foundation (ASF) under one
+# or more contributor license agreements.  See the NOTICE file
+# distributed with this work for additional information
+# regarding copyright ownership.  The ASF licenses this file
+# to you under the Apache License, Version 2.0 (the
+# "License"); you may not use this file except in compliance
+# with the License.  You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
-VERSION=$1
+VERSION="2.1.1"
+SHA1="ba1ce9e7f141e0217cb97238f69157b20cc84e01"
+TARBALL="apache-cassandra-${VERSION}-bin.tar.gz"
+URL="http://www.apache.dist/cassandra/${VERSION}/${TARBALL}"
 
-# Download and extract
-wget http://archive.apache.org/dist/cassandra/$VERSION/apache-cassandra-$VERSION-bin.tar.gz
-tar -xvzf apache-cassandra-$VERSION-bin.tar.gz
-rm -f apache-cassandra-$VERSION-bin.tar.gz
-mv apache-cassandra-$VERSION /root/
-ln -sf /root/apache-cassandra-$VERSION /root/apache-cassandra
+cd /
 
-# Configure
-CONFIG=/root/apache-cassandra/conf/cassandra.yaml
-ENV=/root/apache-cassandra/conf/cassandra-env.sh
-sed -i -e "s/^# num_tokens.*/num_tokens: 256/"      $CONFIG
-sed -i -e "s/^listen_address.*/listen_address: /"   $CONFIG
-sed -i -e "s/^rpc_address.*/rpc_address: 0.0.0.0/"  $CONFIG
-sed -i -e 's/seeds: "127.0.0.1"/seeds: "cass1"/g' $CONFIG
-sed -i -e "s/Xss180k/Xss300k/g" $ENV
+set -e
+set -x
 
+# download the tarball from an Apache mirror
+# verify the checksum
+# untar in /opt, cleanup, symlink to /opt/cassandra
+
+echo "${SHA1} ${TARBALL}" > ${TARBALL}.sha1
+
+ls -l
+
+# copy in from the Dockerfile for now to save downloads
+#curl -O -s ${URL}
+
+sha1sum --check ${TARBALL}.sha1
+
+tar -xzf ${TARBALL} -C /opt
+
+rm -f ${TARBALL} ${TARBALL}.sha1
+
+ln -s /opt/apache-cassandra-$VERSION /opt/cassandra
+
+rm -f $0
